#!/usr/bin/env python3
"""Rebuild the IconScout carousel on the home page.

Usage (from the project folder):
    python3 tools/build-reel.py

What it reads:
    tools/reel.json             the list of animations, in carousel order:
                                file (name of the JSON in assets/iconscout/, without .json),
                                title, collection and url (kept for reference)
    assets/iconscout/*.json     the Lottie files exported from After Effects

What it writes:
    assets/iconscout/reel-data.js   every listed animation in one script, so the reel also
                                    works when index.html is opened from disk
    index.html                      the playlist rows between <!-- reel:start --> and <!-- reel:end -->
                                    (the record on the home plays them in this order, with music)

To replace an animation: overwrite its JSON (same name) and run the script.
To add, remove, rename or reorder: edit tools/reel.json and run the script.
Only Python's standard library is used.
"""
import html
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / 'tools' / 'reel.json'
LOTTIE_DIR = ROOT / 'assets' / 'iconscout'
DATA_JS = LOTTIE_DIR / 'reel-data.js'
INDEX = ROOT / 'index.html'
HEAVY_KB = 150  # a tile above this size slows the section down; worth simplifying in After Effects


def fail(msg):
    sys.exit(f'\n✗ {msg}\nNo se escribió nada.\n')


def load_manifest():
    try:
        items = json.loads(MANIFEST.read_text())
    except FileNotFoundError:
        fail(f'Falta {MANIFEST.relative_to(ROOT)}')
    except json.JSONDecodeError as e:
        fail(f'{MANIFEST.relative_to(ROOT)} no es un JSON válido (línea {e.lineno}): {e.msg}')
    if not isinstance(items, list) or not items:
        fail('tools/reel.json debe ser una lista con al menos una animación')
    for i, it in enumerate(items, 1):
        for key in ('file', 'title', 'collection', 'url'):
            if not str(it.get(key, '')).strip():
                fail(f'El elemento {i} de tools/reel.json no tiene "{key}"')
        it['file'] = it['file'].removesuffix('.json')
    names = [it['file'] for it in items]
    dupes = {n for n in names if names.count(n) > 1}
    if dupes:
        fail(f'Repetidos en tools/reel.json: {", ".join(sorted(dupes))}')
    return items


def load_animations(items):
    data, warnings = {}, []
    for it in items:
        path = LOTTIE_DIR / f'{it["file"]}.json'
        if not path.exists():
            fail(f'"{it["file"]}" está en la lista pero no existe {path.relative_to(ROOT)}')
        try:
            anim = json.loads(path.read_text())
        except json.JSONDecodeError as e:
            fail(f'{path.name} no es un JSON válido (línea {e.lineno}): {e.msg}')
        if not isinstance(anim, dict) or not isinstance(anim.get('layers'), list) or 'w' not in anim:
            fail(f'{path.name} no parece una animación Lottie (le faltan layers/w)')
        if any(isinstance(a, dict) and a.get('p') and not str(a.get('p')).startswith('data:') for a in anim.get('assets', [])):
            warnings.append(f'{path.name} enlaza imágenes externas y no van a cargar. Expórtalo con las imágenes incrustadas o en vectores.')
        kb = path.stat().st_size // 1024
        if kb > HEAVY_KB:
            warnings.append(f'{path.name} pesa {kb} KB (más de {HEAVY_KB} KB); conviene simplificarlo')
        data[it['file']] = anim
    return data, warnings


def track(it, i):
    """One playlist row: side letter + number (A1..A5, B1..B5, C1..), title and collection."""
    e = lambda v: html.escape(str(v), quote=True)
    n = f'{chr(65 + i // 5)}{i % 5 + 1}'
    return (f'          <li><button type="button" data-file="{e(it["file"])}" data-coll="{e(it["collection"])}">'
            f'<span class="n">{n}</span><span>{e(it["title"])}</span><span class="c">{e(it["collection"])}</span></button></li>\n')


def main():
    items = load_manifest()
    data, warnings = load_animations(items)

    page = INDEX.read_text()
    m = re.search(r'(<!-- reel:start[^>]*-->\n)(.*?)(\n\s*<!-- reel:end -->)', page, re.S)
    if not m:
        fail('index.html no tiene los marcadores <!-- reel:start --> / <!-- reel:end --> alrededor del carrusel')
    rows = ''.join(track(it, i) for i, it in enumerate(items))
    page = page[:m.start(2)] + rows.rstrip('\n') + page[m.end(2):]

    js = ('/* The reel\'s Lottie animations. Generated by tools/build-reel.py from tools/reel.json: do not edit.\n'
          '   Loaded as a script (not fetched) so the reel also works when index.html is opened from disk. */\n'
          'window.REEL_DATA = ' + json.dumps(data, separators=(',', ':')) + ';\n')
    DATA_JS.write_text(js)
    INDEX.write_text(page)

    print(f'\n✓ Carrusel actualizado: {len(items)} animaciones, reel-data.js {len(js) // 1024} KB\n')
    for i, it in enumerate(items, 1):
        print(f'  {i:2}. {it["title"]}  ({it["collection"]})  ← {it["file"]}.json')
    unused = sorted(p.stem for p in LOTTIE_DIR.glob('*.json') if p.stem not in data)
    if unused:
        print(f'\n  No están en el carrusel (siguen en assets/iconscout/): {", ".join(unused)}')
    for w in warnings:
        print(f'\n  ! {w}')
    print()


if __name__ == '__main__':
    main()
